// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForkDemo(arg1) {
  return window['go']['main']['App']['ForkDemo'](arg1);
}

export function GetProcessDetail(arg1, arg2) {
  return window['go']['main']['App']['GetProcessDetail'](arg1, arg2);
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}

export function SetPriority(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPriority'](arg1, arg2, arg3);
}

export function SpawnProcess(arg1, arg2) {
  return window['go']['main']['App']['SpawnProcess'](arg1, arg2);
}
