// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSnapshot():Promise<main.SnapshotData>;

export function KillProcess(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetPriority(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SpawnProcess(arg1:string,arg2:Array<string>):Promise<number>;
